[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCpMJn7JAOnxSOS-NeNJPAHw/"
[[redirects]]
  from = "/wtp"
  to = "https://forms.gle/pyaF6yPrCC3LcNaD7"
[[redirects]]
  from = "/sg"
  to = "https://singapore.onepwaa.org"
